/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grupocuatro.proyectoalmacen.vista.ventanas.crudUsuario;

import java.awt.Color;

/**
 *
 * @author manue
 */
public class CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenidoPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        nombreSeparator = new javax.swing.JSeparator();
        contrasenaSeparator = new javax.swing.JSeparator();
        contrasenaField = new javax.swing.JPasswordField();
        contrasenaLabel = new javax.swing.JLabel();
        presioLabel = new javax.swing.JLabel();
        crearButton = new javax.swing.JButton();
        preguntasLabel = new javax.swing.JLabel();
        respuestaField = new javax.swing.JTextField();
        preguntaComboBox = new javax.swing.JComboBox<>();
        tipoUsuarioComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(435, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(435, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenidoPanel.setBackground(new java.awt.Color(242, 174, 48));
        contenidoPanel.setMaximumSize(new java.awt.Dimension(435, 450));
        contenidoPanel.setMinimumSize(new java.awt.Dimension(435, 450));

        tituloLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(217, 11, 49));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("CREAR USUARIO");
        tituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nombreLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("Ingrese el Nombre");

        nombreField.setBackground(new java.awt.Color(242, 174, 48));
        nombreField.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        nombreField.setForeground(new java.awt.Color(153, 153, 153));
        nombreField.setText("Nombre del Usuario");
        nombreField.setBorder(null);
        nombreField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreFieldFocusLost(evt);
            }
        });
        nombreField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreFieldMousePressed(evt);
            }
        });
        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        nombreSeparator.setForeground(new java.awt.Color(0, 0, 0));

        contrasenaSeparator.setForeground(new java.awt.Color(0, 0, 0));

        contrasenaField.setBackground(new java.awt.Color(242, 174, 48));
        contrasenaField.setForeground(new java.awt.Color(153, 153, 153));
        contrasenaField.setText("contrasena");
        contrasenaField.setBorder(null);
        contrasenaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contrasenaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contrasenaFieldFocusLost(evt);
            }
        });
        contrasenaField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasenaFieldMousePressed(evt);
            }
        });

        contrasenaLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        contrasenaLabel.setForeground(new java.awt.Color(255, 255, 255));
        contrasenaLabel.setText("Contraseña");

        presioLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        presioLabel.setForeground(new java.awt.Color(255, 255, 255));
        presioLabel.setText("Seleccione tipo de Usuario");

        crearButton.setBackground(new java.awt.Color(158, 191, 36));
        crearButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        crearButton.setForeground(new java.awt.Color(255, 255, 255));
        crearButton.setText("CREAR");
        crearButton.setBorder(null);
        crearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearButton.setFocusable(false);
        crearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearButtonMouseClicked(evt);
            }
        });
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        preguntasLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        preguntasLabel.setForeground(new java.awt.Color(255, 255, 255));
        preguntasLabel.setText("Seleccione pregunta de seguridad");

        respuestaField.setForeground(new java.awt.Color(204, 204, 204));
        respuestaField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        respuestaField.setText("respuesta");
        respuestaField.setBorder(null);
        respuestaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                respuestaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                respuestaFieldFocusLost(evt);
            }
        });
        respuestaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestaFieldActionPerformed(evt);
            }
        });

        preguntaComboBox.setBorder(null);
        preguntaComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout contenidoPanelLayout = new javax.swing.GroupLayout(contenidoPanel);
        contenidoPanel.setLayout(contenidoPanelLayout);
        contenidoPanelLayout.setHorizontalGroup(
            contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoPanelLayout.createSequentialGroup()
                .addGroup(contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoPanelLayout.createSequentialGroup()
                        .addGroup(contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenidoPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenidoPanelLayout.createSequentialGroup()
                                            .addComponent(nombreLabel)
                                            .addGap(25, 25, 25)
                                            .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenidoPanelLayout.createSequentialGroup()
                                            .addComponent(presioLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                            .addComponent(tipoUsuarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(contenidoPanelLayout.createSequentialGroup()
                                            .addComponent(contrasenaLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(contrasenaSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenidoPanelLayout.createSequentialGroup()
                                            .addGap(170, 170, 170)
                                            .addGroup(contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(contrasenaField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nombreSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(preguntasLabel)))
                            .addGroup(contenidoPanelLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(tituloLabel)))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoPanelLayout.createSequentialGroup()
                        .addComponent(respuestaField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoPanelLayout.createSequentialGroup()
                        .addComponent(preguntaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        contenidoPanelLayout.setVerticalGroup(
            contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tituloLabel)
                .addGap(18, 18, 18)
                .addGroup(contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(nombreLabel))
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(nombreSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contrasenaLabel)
                    .addGroup(contenidoPanelLayout.createSequentialGroup()
                        .addComponent(contrasenaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contrasenaSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(contenidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presioLabel)
                    .addComponent(tipoUsuarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(preguntasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preguntaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respuestaField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(contenidoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 435, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFieldFocusGained
        if(nombreField.getText().equals("Nombre del Usuario")){
            nombreField.setText("");
            nombreField.setForeground(Color.black);
        }
    }//GEN-LAST:event_nombreFieldFocusGained

    private void nombreFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFieldFocusLost
        if(nombreField.getText().equals("Nombre del Usuario")||nombreField.getText().equals("")){
            nombreField.setText("Nombre del Usuario");
            nombreField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nombreFieldFocusLost

    private void nombreFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreFieldMousePressed

    }//GEN-LAST:event_nombreFieldMousePressed

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void contrasenaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrasenaFieldFocusGained
        if(String.valueOf(contrasenaField.getPassword()).equals("contrasena")){
            contrasenaField.setText("");
            contrasenaField.setForeground(Color.black);
        }
    }//GEN-LAST:event_contrasenaFieldFocusGained

    private void contrasenaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrasenaFieldFocusLost
        if(String.valueOf(contrasenaField.getPassword()).equals("contrasena")||String.valueOf(contrasenaField.getPassword()).equals("")){
            contrasenaField.setText("contrasena");
            contrasenaField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_contrasenaFieldFocusLost

    private void contrasenaFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenaFieldMousePressed

    }//GEN-LAST:event_contrasenaFieldMousePressed

    private void crearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearButtonMouseClicked

    }//GEN-LAST:event_crearButtonMouseClicked

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed

    }//GEN-LAST:event_crearButtonActionPerformed

    private void respuestaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuestaFieldActionPerformed

    private void respuestaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_respuestaFieldFocusGained
        if(String.valueOf(respuestaField.getText()).equals("respuesta")){
            respuestaField.setText("");
            respuestaField.setForeground(Color.black);
        }
    }//GEN-LAST:event_respuestaFieldFocusGained

    private void respuestaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_respuestaFieldFocusLost
        if(respuestaField.getText().equals("respuestas")||respuestaField.getText().equals("")){
            respuestaField.setText("respuesta");
            respuestaField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_respuestaFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenidoPanel;
    public javax.swing.JPasswordField contrasenaField;
    private javax.swing.JLabel contrasenaLabel;
    private javax.swing.JSeparator contrasenaSeparator;
    public javax.swing.JButton crearButton;
    public javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JSeparator nombreSeparator;
    public javax.swing.JComboBox<String> preguntaComboBox;
    private javax.swing.JLabel preguntasLabel;
    private javax.swing.JLabel presioLabel;
    public javax.swing.JTextField respuestaField;
    public javax.swing.JComboBox<String> tipoUsuarioComboBox;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
