/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grupocuatro.proyectoalmacen.vista;
import  java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author manue
 */
public class MenuPrincipal extends javax.swing.JFrame {
    protected Date fecha = new Date();
    protected SimpleDateFormat fechaFormato = new SimpleDateFormat("dd/MM/YYYY");
    protected String fechaHoy = fechaFormato.format(fecha);
    private int idProductoSeleccionado;

    public int getIdProductoSeleccionado() {
        return idProductoSeleccionado;
    }

    public void setIdProductoSeleccionado(int idProductoSeleccionado) {
        this.idProductoSeleccionado = idProductoSeleccionado;
    }
    
    

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        fechaLabel.setText(fechaHoy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoJPanel = new javax.swing.JPanel();
        arribaJPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        izquierdaJPanel = new javax.swing.JPanel();
        ingresarStockButton = new javax.swing.JButton();
        verUsuariosButton = new javax.swing.JButton();
        registrarProductoButton = new javax.swing.JButton();
        registroButton = new javax.swing.JButton();
        retirarButton = new javax.swing.JButton();
        infoJPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        nombreLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productosJTable = new javax.swing.JTable();
        salirbutton = new javax.swing.JButton();
        eliminarPButton = new javax.swing.JButton();
        actualizarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 700));

        fondoJPanel.setBackground(new java.awt.Color(242, 174, 48));
        fondoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        arribaJPanel.setBackground(new java.awt.Color(242, 157, 53));
        arribaJPanel.setFocusable(false);
        arribaJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 100)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("HEART FOOD");
        titleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleLabelMouseClicked(evt);
            }
        });
        arribaJPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 6, -1, -1));

        fechaLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(242, 242, 242));
        fechaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaLabel.setText("01/01/2022");
        fechaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        arribaJPanel.add(fechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, -1, -1));

        fondoJPanel.add(arribaJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1000, 150));

        izquierdaJPanel.setBackground(new java.awt.Color(242, 157, 53));
        izquierdaJPanel.setFocusable(false);
        izquierdaJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingresarStockButton.setBackground(new java.awt.Color(158, 191, 36));
        ingresarStockButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        ingresarStockButton.setForeground(new java.awt.Color(255, 255, 255));
        ingresarStockButton.setText("INGRESAR STOCK");
        ingresarStockButton.setBorder(null);
        ingresarStockButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarStockButton.setFocusable(false);
        ingresarStockButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarStockButtonMouseClicked(evt);
            }
        });
        izquierdaJPanel.add(ingresarStockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 140, 170, 50));

        verUsuariosButton.setBackground(new java.awt.Color(158, 191, 36));
        verUsuariosButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        verUsuariosButton.setForeground(new java.awt.Color(255, 255, 255));
        verUsuariosButton.setText("VER USUARIOS");
        verUsuariosButton.setBorder(null);
        verUsuariosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verUsuariosButton.setFocusable(false);
        verUsuariosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verUsuariosButtonMouseClicked(evt);
            }
        });
        izquierdaJPanel.add(verUsuariosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 160, 50));

        registrarProductoButton.setBackground(new java.awt.Color(158, 191, 36));
        registrarProductoButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        registrarProductoButton.setForeground(new java.awt.Color(255, 255, 255));
        registrarProductoButton.setText("REGISTRAR PRODUCTO");
        registrarProductoButton.setBorder(null);
        registrarProductoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarProductoButton.setFocusable(false);
        registrarProductoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarProductoButtonMouseClicked(evt);
            }
        });
        izquierdaJPanel.add(registrarProductoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 70));

        registroButton.setBackground(new java.awt.Color(158, 191, 36));
        registroButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        registroButton.setForeground(new java.awt.Color(255, 255, 255));
        registroButton.setText("VER REGISTRO");
        registroButton.setBorder(null);
        registroButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registroButton.setFocusable(false);
        registroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroButtonMouseClicked(evt);
            }
        });
        izquierdaJPanel.add(registroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 50));

        retirarButton.setBackground(new java.awt.Color(217, 11, 49));
        retirarButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        retirarButton.setForeground(new java.awt.Color(255, 255, 255));
        retirarButton.setText("RETIRAR STOCK");
        retirarButton.setBorder(null);
        retirarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        retirarButton.setFocusable(false);
        retirarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retirarButtonMouseClicked(evt);
            }
        });
        izquierdaJPanel.add(retirarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 160, 50));

        fondoJPanel.add(izquierdaJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 550));

        infoJPanel.setBackground(new java.awt.Color(242, 133, 0));
        infoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        infoJPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, 188, 10));

        nombreLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(242, 242, 242));
        nombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreLabel.setText("Nombre");
        infoJPanel.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, -1));

        tipoLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        tipoLabel.setForeground(new java.awt.Color(242, 242, 242));
        tipoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipoLabel.setText("TipoUsuario");
        infoJPanel.add(tipoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, 190, -1));

        fondoJPanel.add(infoJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 150));

        productosJTable.setBackground(new java.awt.Color(242, 242, 242));
        productosJTable.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        productosJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTO", "DESCRIPCIÓN", "PRECIO", "CANTIDAD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productosJTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        productosJTable.setRowHeight(30);
        productosJTable.setSelectionBackground(new java.awt.Color(153, 153, 153));
        productosJTable.setSelectionForeground(new java.awt.Color(255, 204, 153));
        productosJTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        productosJTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        productosJTable.setShowGrid(true);
        productosJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productosJTable);
        if (productosJTable.getColumnModel().getColumnCount() > 0) {
            productosJTable.getColumnModel().getColumn(0).setMinWidth(90);
            productosJTable.getColumnModel().getColumn(0).setPreferredWidth(90);
            productosJTable.getColumnModel().getColumn(0).setMaxWidth(90);
            productosJTable.getColumnModel().getColumn(1).setMinWidth(230);
            productosJTable.getColumnModel().getColumn(1).setPreferredWidth(230);
            productosJTable.getColumnModel().getColumn(1).setMaxWidth(230);
            productosJTable.getColumnModel().getColumn(2).setMinWidth(360);
            productosJTable.getColumnModel().getColumn(2).setPreferredWidth(360);
            productosJTable.getColumnModel().getColumn(2).setMaxWidth(360);
            productosJTable.getColumnModel().getColumn(3).setMinWidth(120);
            productosJTable.getColumnModel().getColumn(3).setPreferredWidth(120);
            productosJTable.getColumnModel().getColumn(3).setMaxWidth(120);
            productosJTable.getColumnModel().getColumn(4).setMinWidth(105);
            productosJTable.getColumnModel().getColumn(4).setPreferredWidth(105);
            productosJTable.getColumnModel().getColumn(4).setMaxWidth(105);
        }

        fondoJPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 910, -1));

        salirbutton.setBackground(new java.awt.Color(217, 11, 49));
        salirbutton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        salirbutton.setForeground(new java.awt.Color(255, 255, 255));
        salirbutton.setText("SALIR SESIÓN");
        salirbutton.setBorder(null);
        salirbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirbutton.setFocusable(false);
        salirbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirbuttonMouseClicked(evt);
            }
        });
        fondoJPanel.add(salirbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 630, 160, 50));

        eliminarPButton.setBackground(new java.awt.Color(217, 11, 49));
        eliminarPButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        eliminarPButton.setForeground(new java.awt.Color(255, 255, 255));
        eliminarPButton.setText("ELIMINAR PRODUCTO");
        eliminarPButton.setBorder(null);
        eliminarPButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarPButton.setFocusable(false);
        eliminarPButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarPButtonMouseClicked(evt);
            }
        });
        fondoJPanel.add(eliminarPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, 200, 70));

        actualizarButton.setBackground(new java.awt.Color(158, 191, 36));
        actualizarButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        actualizarButton.setForeground(new java.awt.Color(255, 255, 255));
        actualizarButton.setText("ACTUALIZAR");
        actualizarButton.setBorder(null);
        actualizarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizarButton.setFocusable(false);
        actualizarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarButtonMouseClicked(evt);
            }
        });
        fondoJPanel.add(actualizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 630, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroButtonMouseClicked

    }//GEN-LAST:event_registroButtonMouseClicked

    private void salirbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_salirbuttonMouseClicked

    private void retirarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retirarButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_retirarButtonMouseClicked

    private void ingresarStockButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarStockButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarStockButtonMouseClicked

    private void eliminarPButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarPButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarPButtonMouseClicked

    private void verUsuariosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verUsuariosButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_verUsuariosButtonMouseClicked

    private void actualizarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarButtonMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_actualizarButtonMouseClicked

    private void registrarProductoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarProductoButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarProductoButtonMouseClicked

    private void productosJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosJTableMouseClicked

    }//GEN-LAST:event_productosJTableMouseClicked

    private void titleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleLabelMouseClicked
        // TODO 
    }//GEN-LAST:event_titleLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizarButton;
    private javax.swing.JPanel arribaJPanel;
    public javax.swing.JButton eliminarPButton;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JPanel fondoJPanel;
    private javax.swing.JPanel infoJPanel;
    public javax.swing.JButton ingresarStockButton;
    private javax.swing.JPanel izquierdaJPanel;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel nombreLabel;
    public javax.swing.JTable productosJTable;
    public javax.swing.JButton registrarProductoButton;
    public javax.swing.JButton registroButton;
    public javax.swing.JButton retirarButton;
    public javax.swing.JButton salirbutton;
    public javax.swing.JLabel tipoLabel;
    private javax.swing.JLabel titleLabel;
    public javax.swing.JButton verUsuariosButton;
    // End of variables declaration//GEN-END:variables
}
